#!/bin/sh
set -eu
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -v app_password="$DB_APP_PASSWORD" <<'SQL'
CREATE ROLE csi_app LOGIN PASSWORD :'app_password';
GRANT CONNECT ON DATABASE csi TO csi_app;
GRANT USAGE ON SCHEMA public TO csi_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO csi_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO csi_app;
CREATE EXTENSION IF NOT EXISTS vector;
SQL
